provider:
  name: faas
  gateway: http://127.0.0.1:8080

functions:
  kollector:
    lang: node8-express
    handler: ./kollector
    image: openfaas/kollector:latest
  latest-release:
    lang: go
    handler: ./latest-release
    image: alexellis/latest-release:0.1
  s3:
    lang: go
    handler: ./s3
    image: openfaas/s3:0.2
  signup:
    lang: golang-middleware
    handler: ./signup
    image: signup:latest
  slack:
    lang: golang-middleware
    handler: ./slack
    image: slack:latest
