provider:
  name: faas
  gateway: http://127.0.0.1:8080

functions:
  latest-release:
    lang: go
    handler: ./latest-release
    image: alexellis/latest-release:0.1
    environment:
      write_debug: true
      content_type: text/html
  s3:
    lang: go
    handler: ./s3
    image: openfaas/s3:latest
    secrets:
      - openfaas-s3

